name: Gokart-Web Application Workflow

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths:
      - 'rakieta/**'
      - '.github/workflows/gokart-web.yaml'
  push:
    branches: [ main ]
    paths:
      - 'rakieta/**'
      - '.github/workflows/gokart-web.yaml'

env:
  AZURE_FUNCTIONAPP_NAME: 'gokart-web'   # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './rakieta'       # set this to the path to your function app project, defaults to the repository root
  NODE_VERSION: '20.x'                      # set this to the node version to use (e.g. '8.x', '10.x', '12.x')

jobs:
  project-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Choose the Node.js version that matches your project requirements

      - name: Install dependencies
        working-directory: rakieta
        run: |
          npm install
          npm ci

      - name: Lint and unit test
        working-directory: rakieta
        run: |
          npm run test:unit
          npm run lint

#      - name: E2E test using cypress -- not working due not responding browser in github actions
#        working-directory: rakieta
#        run: |
#          npm run test:e2e

  docker-build:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs:
      - project-build

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: rakieta
        run: npm install # or use yarn install if you are using Yarn

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile # Ensure this Dockerfile is set up for your Vue.js app
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.APPLICATION_NAME }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.APPLICATION_NAME }}:${{ github.sha }}

  deploy-azure:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: 'Deploy to Azure WebApp'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}