name: Node.js CI for Pull Requests

# This workflow is triggered on pull requests to the main branch
on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Necessary for merge conflict check

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: rakieta
        run: npm install

      - name: Run tests
        working-directory: rakieta
        run: npm test:unit

      - name: Check for merge conflicts
        run: |
          git fetch origin main
          git merge origin/main --no-commit --no-ff
